[package]
name = "snarky-deriver"
description = "Derive macros for the snarky circuit-writing DSL (#[derive(SnarkyType)])"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
itertools.workspace = true
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full", "extra-traits"] }
